project:
  type: website

website:
  title: "Discursus"
  site-url: https://blog.discurs.us
  description: "Some things I have written down"
  navbar:
    right:
      - about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/serapio
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/lucien-carroll/
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@serapio
      - icon: rss
        href: index.xml
        
format:
  html:
    theme: vapor
    css: styles.css
  
resources: 
  - CNAME

editor: visual

